name: Build Pack
on:
  push:
    branches:
      - master # master 分支 push 时触发工作流
    paths:
      - '.github/workflows/main.yml'
jobs:
  pack: # 打包任务
    runs-on: windows-latest # 在 windows 系统中运行

    steps:
      - name: Check Out Code # 安装依赖并且进行构建
        uses: actions/checkout@v2 # 下载仓库代码到工作流机器中

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 使用合适的Node.js版本，根据你的项目需求

      - name: Install Dependencies && Build
        run: |
          cd ./frontend/
          npm install
          npm run build
          cd ..
          npm install
          npm run rd
          npm run build-wz-64

      - name: Upload File Artifact # 将构建产物进行上传
        uses: actions/upload-artifact@v4.6.2
        with:
          name: SDT # 上传后的名字
          path: ./out/净水处理智慧交互设计软件-win-3.9.1-x64.7z # 将 out 目录进行上传